### PR TITLE
Replaced jf kernel

### PR DESCRIPTION
**Pull request by vbajs**
So it can work with jfltexx, jfvelte and jfltetmo (i9505,19515 and M919)

### CODE REVIEW

**Comment by akhilnarang** [comment]
@srisurya95 told me jfvelte won't work with jflte kernel

**Comment by vbajs** [comment]
OK, just ignore "jfvelte", its a silly misunderstanding :p

**Comment by akhilnarang** [comment]
Wait then
I will update that kernel soon, and your device trees so they'll build and boot

**Comment by vbajs** [comment]
But the kernel will work for jfltexx and jfltetmo

**Comment by vbajs** [comment]
Okeh

**Comment by srisurya95** [comment]
Jfltexx will work with jfvelte kernel ....jfve uses it's own deconfig so nothing is broken

**Comment by vbajs** [comment]
And jfltetmo too? Because in its ROMs, I think it uses jfltexx kernel so that means
Jfvelte kernel = jfltexx kernel = jfltetmo kernel

**Comment by srisurya95** [comment]
idk about that meh..

**Pull request merged**
